variable "company" {}
variable "env" {}
variable "app" {}
variable "vpc_private_subnets_map" {}
variable "vpc_list" {}
variable "mysql_security_group" {}
variable "outbound_security_group" {}
variable "db_instance_class" {}
variable "db_name" {}
variable "applications" {}
variable "db_applications" {}
