variable "company" {}
variable "app" {}
variable "region" {}
variable "azs" {}
variable "applications" {}
variable "services" {}
variable "env" {}
variable "subnets" {}
variable "ssh_security_group" {}
variable "http_security_group" {}
variable "https_security_group" {}
variable "nfs_security_group" {}
variable "flask_security_group" {}
variable "outbound_security_group" {}
variable "dns_zone_id" {}
variable "domain_name" {}
variable "ec2_ami_id" {}
variable "ec2_instance_type" {}
variable "ec2_asg_size" {}
variable "ec2_spot_prices" {}
variable "efs_file_system" {}
variable "vpc_list" {}
variable "certificate_arn" {}
variable "db_server_endpoint" {}
variable "cloudfront_endpoint" {}
